# Generated by Django 4.2.9 on 2026-02-07 18:17

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='bot_avatars/', verbose_name='Аватар')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('vk', 'VK')], max_length=20, verbose_name='Платформа')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'На паузе'), ('inactive', 'Неактивен'), ('waiting_code', 'Ожидание кода'), ('error', 'Ошибка')], default='inactive', max_length=20, verbose_name='Статус')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('phone_code_hash', models.CharField(blank=True, max_length=500, verbose_name='Хеш кода')),
                ('session_string', models.TextField(blank=True, null=True, verbose_name='Session String')),
                ('api_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=100, verbose_name='API Hash')),
                ('telegram_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('whatsapp_token', models.CharField(blank=True, max_length=200, verbose_name='WhatsApp Token')),
                ('system_prompt', models.TextField(default='Ты - полезный AI ассистент. Отвечай четко и по существу.', verbose_name='Системный промпт')),
                ('openai_model', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='Модель OpenAI')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=500, verbose_name='Max tokens')),
                ('use_rag', models.BooleanField(default=True, verbose_name='Использовать базу знаний (RAG)')),
                ('rag_top_k', models.IntegerField(default=5, verbose_name='Количество релевантных фрагментов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'db_table': 'bot_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='ID пользователя в мессенджере', max_length=200, verbose_name='ID пользователя')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Имя пользователя')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Лид')),
                ('lead_email', models.EmailField(blank=True, max_length=254, verbose_name='Email лида')),
                ('lead_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон лида')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало диалога')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее сообщение')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.botagent', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.CharField(choices=[('bitrix24', 'Bitrix24'), ('amocrm', 'AmoCRM'), ('moysklad', 'МойСклад'), ('google_sheets', 'Google Sheets')], max_length=20, verbose_name='Тип CRM')),
                ('status', models.CharField(choices=[('disconnected', 'Отключено'), ('connecting', 'Подключение...'), ('connected', 'Подключено'), ('error', 'Ошибка')], default='disconnected', max_length=20, verbose_name='Статус')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен/URL')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена')),
                ('webhook_url', models.CharField(blank=True, max_length=500, verbose_name='Webhook URL')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255, verbose_name='ID таблицы')),
                ('sheet_name', models.CharField(blank=True, default='Sheet1', max_length=100, verbose_name='Название листа')),
                ('credentials_json', models.TextField(blank=True, verbose_name='Google Credentials JSON')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('leads_synced', models.IntegerField(default=0, verbose_name='Синхронизировано лидов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Интеграция',
                'verbose_name_plural': 'CRM Интеграции',
                'db_table': 'crm_integrations',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to=core.models.knowledge_base_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text'), ('md', 'Markdown')], max_length=10, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('is_indexed', models.BooleanField(default=False, help_text='Документ разбит на фрагменты и векторизован', verbose_name='Проиндексирован')),
                ('chunks_count', models.IntegerField(default=0, verbose_name='Количество фрагментов')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата индексации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.botagent', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'База знаний',
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_lead', 'Создание лида'), ('update_lead', 'Обновление лида'), ('create_contact', 'Создание контакта'), ('create_order', 'Создание заказа'), ('sync_products', 'Синхронизация товаров'), ('append_row', 'Добавление строки'), ('sync_all', 'Полная синхронизация')], max_length=50, verbose_name='Действие')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('pending', 'В процессе')], default='pending', max_length=20, verbose_name='Статус')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Ответ')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.crmintegration')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'db_table': 'crm_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('conversations_count', models.IntegerField(default=0, verbose_name='Количество диалогов')),
                ('leads_count', models.IntegerField(default=0, verbose_name='Количество лидов')),
                ('messages_count', models.IntegerField(default=0, verbose_name='Количество сообщений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.botagent', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'db_table': 'analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('bot', 'Бот'), ('system', 'Система')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'), models.Index(fields=['role', 'created_at'], name='messages_role_c5c560_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст фрагмента')),
                ('embedding', pgvector.django.VectorField(dimensions=1536, verbose_name='Вектор')),
                ('chunk_index', models.IntegerField(help_text='Порядковый номер фрагмента в документе', verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgebase', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Фрагмент документа',
                'verbose_name_plural': 'Фрагменты документов',
                'db_table': 'knowledge_chunks',
                'ordering': ['knowledge_base', 'chunk_index'],
                'indexes': [models.Index(fields=['knowledge_base', 'chunk_index'], name='knowledge_c_knowled_ae8c59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['bot', 'is_indexed'], name='knowledge_b_bot_id_76e78d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmintegration',
            unique_together={('user', 'crm_type')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot', 'user_id'], name='conversatio_bot_id_557761_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot', 'is_lead'], name='conversatio_bot_id_c25b75_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_at'], name='conversatio_started_0026ec_idx'),
        ),
        migrations.AddIndex(
            model_name='botagent',
            index=models.Index(fields=['user', 'status'], name='bot_agents_user_id_c4dd74_idx'),
        ),
        migrations.AddIndex(
            model_name='botagent',
            index=models.Index(fields=['platform'], name='bot_agents_platfor_8b6aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['bot', 'date'], name='analytics_bot_id_859373_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('bot', 'date')},
        ),
    ]
