# Generated by Django 4.2.9 on 2026-02-08 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgebase',
            name='knowledge_b_bot_id_76e78d_idx',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='bot',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='bots',
            field=models.ManyToManyField(blank=True, related_name='knowledge_base', to='core.botagent', verbose_name='Боты'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['user', 'is_indexed'], name='knowledge_b_user_id_ffb265_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['created_at'], name='knowledge_b_created_720dcc_idx'),
        ),
    ]
