# Generated by Django 4.2.9 on 2026-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_knowledgebase_knowledge_b_bot_id_76e78d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botagent',
            name='company_name',
            field=models.CharField(default='TheCloser', help_text='Название компании, от лица которой выступает бот', max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='botagent',
            name='openai_model',
            field=models.CharField(choices=[('gpt-3.5-turbo-0125', 'GPT-3.5 Turbo (Moderate)'), ('gpt-4o-2024-08-06', 'GPT-4o (Moderate)'), ('gpt-4o-mini-2024-07-18', 'GPT-4o mini (Moderate)'), ('o1-mini-2024-09-12', 'o1 mini (Moderate)'), ('o3-mini-2025-01-31', 'o3 mini (Moderate)'), ('o1-2024-12-17', 'o1 (Very Expensive)'), ('gpt-4.1-2025-04-14', 'GPT-4.1 (Moderate)'), ('gpt-5-nano-2025-08-07', 'GPT-5 Nano (Cheap)'), ('gpt-5-mini-2025-08-07', 'GPT-5 Mini (Cheap)'), ('gpt-5-2025-08-07', 'GPT-5 (Moderate)'), ('gpt-5.2-2025-12-11', 'GPT-5.2 (Expensive)')], default='gpt-4o-mini-2024-07-18', max_length=50, verbose_name='Модель OpenAI'),
        ),
    ]
