# Generated by Django 4.2.9 on 2026-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botagent_company_name_alter_botagent_openai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botagent',
            name='openai_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo (Cheap)'), ('gpt-3.5-turbo-0125', 'GPT-3.5 Turbo 0125 (Cheap)'), ('gpt-4-turbo', 'GPT-4 Turbo (Moderate)'), ('gpt-4-turbo-2024-04-09', 'GPT-4 Turbo (Apr 2024) (Moderate)'), ('gpt-4o', 'GPT-4o (Moderate) ⭐'), ('gpt-4o-2024-11-20', 'GPT-4o (Nov 2024) (Moderate)'), ('gpt-4o-2024-08-06', 'GPT-4o (Aug 2024) (Moderate)'), ('gpt-4o-2024-05-13', 'GPT-4o (May 2024) (Moderate)'), ('gpt-4o-mini', 'GPT-4o mini (Cheap) 🔥'), ('gpt-4o-mini-2024-07-18', 'GPT-4o mini (Jul 2024) (Cheap)'), ('gpt-4', 'GPT-4 (Expensive)'), ('gpt-4-0613', 'GPT-4 0613 (Expensive)'), ('o1-mini-2024-09-12', 'o1 mini (Moderate) 🧠'), ('o1-2024-12-17', 'o1 (Very Expensive) 🧠'), ('o3-mini-2025-01-31', 'o3 mini (Moderate) 🧠'), ('gpt-4.1-2025-04-14', 'GPT-4.1 (Moderate)'), ('gpt-5-nano-2025-08-07', 'GPT-5 Nano (Cheap) 🚀'), ('gpt-5-mini-2025-08-07', 'GPT-5 Mini (Cheap) 🚀'), ('gpt-5-2025-08-07', 'GPT-5 (Moderate) 🚀'), ('gpt-5.2-2025-12-11', 'GPT-5.2 (Expensive) 🚀')], default='gpt-4o-mini', max_length=50, verbose_name='Модель OpenAI'),
        ),
    ]
