# Generated by Django 4.2.9 on 2026-02-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_botagent_openai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lead_data',
            field=models.JSONField(blank=True, default=dict, help_text='Все собранные данные от клиента (имя, телефон, дата, бюджет и т.д.)', verbose_name='Данные лида'),
        ),
        migrations.CreateModel(
            name='BotFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: save_client_info, request_human_help', max_length=100, verbose_name='Техническое имя')),
                ('description', models.TextField(help_text='Инструкция: когда AI должен вызвать эту функцию', verbose_name='Описание для AI')),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON: какие данные должен собрать AI (имя, телефон, дата и т.д.)', verbose_name='Схема параметров')),
                ('function_type', models.CharField(choices=[('save_lead', 'Сохранить лид'), ('call_manager', 'Позвать менеджера')], max_length=50, verbose_name='Тип функции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='core.botagent', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Функция бота',
                'verbose_name_plural': 'Функции ботов',
                'db_table': 'bot_functions',
                'ordering': ['bot', 'name'],
                'unique_together': {('bot', 'name')},
            },
        ),
    ]
