# Generated by Django 4.2.9 on 2026-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversation_lead_data_botfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='botagent',
            name='notification_recipient',
            field=models.CharField(blank=True, help_text='Юзернейм в Telegram (например: @TheRizaev). Если пусто — шлет в Избранное.', max_length=100, null=True, verbose_name='Куда слать уведомления'),
        ),
    ]
